# Generated by Django 3.1.7 on 2022-04-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vacinação'},
        ),
        migrations.AlterModelOptions(
            name='vaccineregistration',
            options={'verbose_name': 'Registro Vacinação'},
        ),
    ]
