# Generated by Django 3.1.7 on 2022-04-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220407_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vacinação', 'verbose_name_plural': 'Registro Vacinações'},
        ),
        migrations.AlterModelOptions(
            name='vaccineregistration',
            options={'verbose_name': 'Registro Vacina', 'verbose_name_plural': 'Registro Vacinas'},
        ),
    ]
