# Generated by Django 3.1.7 on 2022-04-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220407_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vacinação', 'verbose_name_plural': 'Registro de Vacinações'},
        ),
        migrations.AlterModelOptions(
            name='vaccineregistration',
            options={'verbose_name': 'Registro Vacina', 'verbose_name_plural': 'Registro de Vacinas'},
        ),
    ]
