# Generated by Django 3.1.7 on 2022-04-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Descrição')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridade')),
                ('color', models.CharField(choices=[('VM', 'Vermelho'), ('LA', 'Laranja'), ('AM', 'Amarelo'), ('VD', 'Verde'), ('AZ', 'Azul'), ('BR', 'Branco')], default='BR', max_length=2, verbose_name='Cor Associada')),
                ('allergygroup', models.ManyToManyField(blank=True, to='core.AllergyGroup', verbose_name='Grupos de Alergia')),
                ('allergyreactiongroup', models.ManyToManyField(blank=True, to='core.AllergyReactionGroup', verbose_name='Grupos de Reação')),
                ('bloodpressurerange', models.ManyToManyField(blank=True, to='core.BloodPressureRange', verbose_name='Faixas de Pressão Arterial')),
                ('comorbiditygroup', models.ManyToManyField(blank=True, to='core.ComorbidityGroup', verbose_name='Grupos de Comorbidade')),
                ('heartrate', models.ManyToManyField(blank=True, to='core.HeartRate', verbose_name='Faixas de Frequência Cardíaca')),
                ('homeusemedicationgroup', models.ManyToManyField(blank=True, to='core.HomeUseMedicationGroup', verbose_name='Grupos Medicação de Uso Doméstico')),
                ('imcclassification', models.ManyToManyField(blank=True, to='core.ImcClassification', verbose_name='Classificações IMC')),
                ('motorresponselevel', models.ManyToManyField(blank=True, to='core.MotorResponseLevel', verbose_name='Níveis de Resposta Motora')),
                ('ocularopeninglevel', models.ManyToManyField(blank=True, to='core.OcularOpeningLevel', verbose_name='Níveis de Abertura Ocular')),
                ('otherassociatedfactor', models.ManyToManyField(blank=True, to='core.OtherAssociatedFactor', verbose_name='Outros fatores associados')),
                ('oximetryrange', models.ManyToManyField(blank=True, to='core.OximetryRange', verbose_name='Faixas de Oximetria')),
                ('painclassification', models.ManyToManyField(blank=True, to='core.PainClassification', verbose_name='Classificações de Dor')),
                ('period', models.ManyToManyField(blank=True, to='core.Period', verbose_name='Períodos')),
                ('peripheralcapillarybloodglucose', models.ManyToManyField(blank=True, to='core.PeripheralCapillaryBloodGlucose', verbose_name='Faixas de Glicemia Capilar Periférica')),
                ('previoussurgerygroup', models.ManyToManyField(blank=True, to='core.PreviousSurgeryGroup', verbose_name='Grupos de Cirurgia Prévia')),
                ('pupilevaluationlevel', models.ManyToManyField(blank=True, to='core.PupilEvaluationLevel', verbose_name='Níveis de Avaliação Pupilar')),
                ('respiratoryfrequency', models.ManyToManyField(blank=True, to='core.RespiratoryFrequency', verbose_name='Faixas de Frequência Respiratória')),
                ('screeningflowchart', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.screeningflowchart', verbose_name='Fluxograma')),
                ('symptom', models.ManyToManyField(blank=True, to='core.Symptom', verbose_name='Sintomas')),
                ('symptomgroup', models.ManyToManyField(blank=True, to='core.SymptomGroup', verbose_name='Grupos de Sintomas')),
                ('temperaturerange', models.ManyToManyField(blank=True, to='core.TemperatureRange', verbose_name='Faixas de Temperatura')),
                ('verbalresponselevel', models.ManyToManyField(blank=True, to='core.VerbalResponseLevel', verbose_name='Níveis de Resposta Verbal')),
            ],
            options={
                'verbose_name': 'Regra de Classificação',
                'verbose_name_plural': 'Regras de Classificação',
                'ordering': ('screeningflowchart', 'priority'),
            },
        ),
    ]
